import = ["~/.config/alacritty/rose-pine.toml"]

[env]
term = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

size = 11.75
offset = { x = 0, y = 6 }

[window]
padding = { x = 8, y = 16 }
decorations = "Transparent"
opacity = 0.96
blur = true
startup_mode = "Maximized"
