import = ["~/.config/alacritty/rose-pine.toml"]

[env]
term = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

size = 11.75
offset = { x = 0, y = 5 }
glyph_offset = { x = 0, y = 2 }

[window]
padding = { x = 8, y = 8 }
decorations = "Full"
opacity = 0.96
blur = true
startup_mode = "Maximized"
